stages:
  - static-test
  - general-test

image: python:3.8

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  key:
    files:
      - poetry.lock
      - .gitlab-ci.yml
    prefix: ${CI_JOB_NAME}
  paths:
    - .cache/pip
    - .venv/

#before_script:
#  - python --version
#  - pip install poetry
#  - poetry config virtualenvs.in-project true
#  - poetry install --no-root

stat-tests:
  stage: static-test
  script:
    - pip install flake8 mypy
    - flake8 ${MLOPS_CODE_PATH}
    - flake8 ${FASTAPI_CODE_PATH}
    - mypy --ignore-missing-imports ${MLOPS_CODE_PATH}
    - mypy --ignore-missing-imports ${FASTAPI_CODE_PATH}

g-tests:
  stage: general-test
  only:
    - tests
  script:
    - python --version
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install --no-root
    - poetry run dvc pull
    - poetry run dvc repro
    - poetry run pytest --disable-warnings
